[package]
name = "label_propagation_iris_example"
version = "0.1.0"
authors = ["vaaaaanquish <6syun9@gmail.com>"]

[dependencies]
label-propagation = { path = "../../" }
ndarray = "0.15.3"
ndarray-stats = "0.5.0"
smartcore = "0.2.0"
rand = "0.8.4"
