[package]
name = "label_propagation_lgc_example"
version = "0.1.0"
authors = ["vaaaaanquish <6syun9@gmail.com>"]

[dependencies]
label-propagation = { path = "../../" }
ndarray = "0.15.3"
ndarray-stats = "0.5.0"
